#!/usr/bin/env python3
"""Export a build_pyramid.py pyramid to Deep Zoom (DZI) for OpenSeadragon.

The on-disk formats are near-identical (tile pyramid, power-of-two levels,
overlap borders), so this mostly re-crops and renames:

  * DZI numbers levels the other way: level N = full res, level 0 = 1x1 px,
    with N = ceil(log2(max(W, H))). Our L0..Lmax map to DZI N..N-Lmax, and
    the missing sub-256px levels are generated by downscaling the root tile.
  * DZI tiles are named {col}_{row}, ours {row}_{col}.
  * DZI edge tiles are NOT padded: an edge tile carries overlap only on
    sides that have neighbors. Our stored tiles are always
    (tile+2*border)^2 with edge replication, so each tile is cropped to
    the exact region DZI expects.

Writes <out>/image.dzi, <out>/image_files/, and a viewer.html using
OpenSeadragon from CDN. Serve with `python3 -m http.server` and open
http://localhost:8000/<out>/viewer.html
"""
import argparse
import json
import math
import shutil
from pathlib import Path

from PIL import Image

DZI_XML = """<?xml version="1.0" encoding="UTF-8"?>
<Image xmlns="http://schemas.microsoft.com/deepzoom/2008"
       TileSize="{tile}" Overlap="{overlap}" Format="{fmt}">
  <Size Width="{w}" Height="{h}"/>
</Image>
"""

VIEWER_HTML = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>DZI viewer</title>
<script src="https://cdn.jsdelivr.net/npm/openseadragon@4.1/build/openseadragon/openseadragon.min.js"></script>
<style>html,body{margin:0;height:100%}#osd{width:100%;height:100%;background:#111}</style>
</head><body><div id="osd"></div>
<script>
window.viewer = OpenSeadragon({
  id: "osd",
  tileSources: "image.dzi",
  prefixUrl: "https://cdn.jsdelivr.net/npm/openseadragon@4.1/build/openseadragon/images/",
  showNavigator: true,
});
</script></body></html>
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("pyramid_pos", nargs="?", metavar="PYRAMID",
                    help="pyramid directory (same as --pyramid)")
    ap.add_argument("--pyramid", default="test_image_16k_pyramid")
    ap.add_argument("--out", default=None,
                    help="output dir (default: <pyramid>_dzi)")
    args = ap.parse_args()

    pdir = Path(args.pyramid)
    meta = json.loads((pdir / "meta.json").read_text())
    W = meta.get("image_width", meta.get("image_size"))
    H = meta.get("image_height", meta.get("image_size"))
    T, B, fmt, n_levels = (meta["tile_size"], meta["border"],
                           meta["format"], meta["levels"])

    out = Path(args.out or f"{pdir.name}_dzi")
    if out.exists():
        shutil.rmtree(out)
    files = out / "image_files"
    files.mkdir(parents=True)

    max_level = math.ceil(math.log2(max(W, H)))

    # our levels -> DZI levels max_level .. max_level - (n_levels-1)
    w, h = W, H
    for l in range(n_levels):
        ldir = files / str(max_level - l)
        ldir.mkdir()
        nx, ny = -(-w // T), -(-h // T)
        for ty in range(ny):
            for tx in range(nx):
                src = Image.open(pdir / f"L{l}" / f"{ty}_{tx}.{fmt}")
                x0, y0 = tx * T - B, ty * T - B
                tile = src.crop((max(x0, 0) - x0, max(y0, 0) - y0,
                                 min((tx + 1) * T + B, w) - x0,
                                 min((ty + 1) * T + B, h) - y0))
                tile.save(ldir / f"{tx}_{ty}.{fmt}")
        print(f"DZI level {max_level - l}: {nx}x{ny} tiles")
        w, h = -(-w // 2), -(-h // 2)

    # sub-root levels (single ever-smaller tile) from the root tile payload
    root = Image.open(pdir / f"L{n_levels - 1}" / f"0_0.{fmt}")
    rscale = 2 ** (n_levels - 1)
    rw, rh = -(-W // rscale), -(-H // rscale)
    cur = root.crop((B, B, B + rw, B + rh))
    for dzl in range(max_level - n_levels, -1, -1):
        scale = 2 ** (max_level - dzl)
        sw, sh = max(-(-W // scale), 1), max(-(-H // scale), 1)
        cur = cur.resize((sw, sh), Image.LANCZOS)
        ldir = files / str(dzl)
        ldir.mkdir()
        cur.save(ldir / f"0_0.{fmt}")

    (out / "image.dzi").write_text(
        DZI_XML.format(tile=T, overlap=B, fmt=fmt, w=W, h=H))
    (out / "viewer.html").write_text(VIEWER_HTML)
    print(f"wrote {out}/image.dzi, image_files/, viewer.html\n"
          f"serve: python3 -m http.server  ->  "
          f"http://localhost:8000/{out}/viewer.html")


if __name__ == "__main__":
    main()
